name: Build and Deploy Documentation

on:
  push:
    branches: [main]
    paths:
      - 'src_docs/**'
      - 'src/claif_cla/**'
      - '.github/workflows/docs.yml'
  pull_request:
    branches: [main]
    paths:
      - 'src_docs/**'
      - 'src/claif_cla/**'
      - '.github/workflows/docs.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-docs:
    name: Build Documentation
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src_docs
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install UV
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
          python-version: "3.12"
          enable-cache: true

      - name: Install MkDocs and dependencies
        run: |
          uv pip install --system mkdocs mkdocs-material
          uv pip install --system mkdocs-minify-plugin
          uv pip install --system pymdown-extensions

      - name: Verify MkDocs config
        run: mkdocs config

      - name: Build documentation
        run: mkdocs build --verbose --strict

      - name: Verify build output
        run: |
          ls -la ../docs/
          test -f ../docs/index.html || (echo "index.html not found" && exit 1)
          test -f ../docs/.nojekyll || (echo ".nojekyll not found" && exit 1)

      - name: Upload documentation artifacts
        uses: actions/upload-artifact@v4
        with:
          name: documentation-site
          path: docs/
          retention-days: 5

      - name: Setup Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/configure-pages@v3

      - name: Upload to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v2
        with:
          path: docs/

  deploy-docs:
    name: Deploy to GitHub Pages
    if: github.ref == 'refs/heads/main'
    needs: build-docs
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

  link-check:
    name: Check Documentation Links
    needs: build-docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download documentation artifacts
        uses: actions/download-artifact@v4
        with:
          name: documentation-site
          path: docs/

      - name: Install link checker
        run: npm install -g linkinator

      - name: Start local server
        run: |
          cd docs
          python -m http.server 8000 &
          sleep 5

      - name: Check internal links
        run: |
          linkinator http://localhost:8000 \
            --recurse \
            --verbosity error \
            --skip "mailto:" \
            --skip "tel:" \
            --skip "javascript:" \
            --timeout 10000

      - name: Check for broken anchors
        run: |
          # Check for broken markdown links
          find src_docs/md -name "*.md" -exec grep -l "\[.*\](" {} \; | \
          xargs grep -n "\[.*\](" | \
          grep -v "http" | \
          grep -v "mailto" | \
          head -20